name: PoC CI/CD Pipeline - CENABAST

on:
  push:
    branches: [ "main", "master" ]

jobs:
  docker-ghcr:
    runs-on: [self-hosted, linux, ubuntu]
    permissions:
      contents: read
      packages: write

    steps:
      - name: 1. Checkout del Código
        uses: actions/checkout@v4

      - name: 2. Autenticación en GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    # ─── AGREGAR ESTOS DOS PASOS NUEVOS ───
      - name: 3. Configurar QEMU (Soporte multiplataforma)
        uses: docker/setup-qemu-action@v3

      - name: 4. Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 5. Construcción y Publicación de la Imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/pruebas-de-task:latest
            ghcr.io/${{ github.repository_owner }}/pruebas-de-task:${{ github.sha }}